### ISSUE TITLE
Different Average

### ISSUE THREAD

**Issue by LinkFoxMario64** [czielinski/portfolioopt#2]
Hey there Christian,

we use your tool and get the same results as you do.
But when i calculate the portfolio-weights with my Excel-Solver i get different results.

Maybe the reason is that we calculate the average differently.
When i calculate the average returns for asset_a in Excel i get 0,008056.
In your examply.py the average for asset_a is -0,001237.

Can you please tell me how you get this average?

Thank you in advance and thank you for the good work!
LinkFoxMario64

**Comment by czielinski** [comment]
I checked that Excel indeed also calculates _-0.001237_ as the mean for Asset A, so I'm not sure what you calculated.
