### ISSUE TITLE
Hi, Thanks in advance for our work.

### ISSUE THREAD

**Issue by B00mGit** [czielinski/portfolioopt#4]
Thanks in advance for your work.
As mentioned in the issue title I'm failing the building wheel for cvxopt.
I'm on a Windows 7 system and I'm installing to a Python 3.5 environment with:
`pip3 install portfolioopt`
If you need further info let me know.
Thx

**Comment by czielinski** [comment]
@B00mGit, the resulting error message would be very helpful.

**Comment by czielinski** [comment]
Cannot be reproduced.
