### ISSUE TITLE
pip installation gives error

### ISSUE THREAD

**Issue by mbzand** [czielinski/portfolioopt#8]
Hi, 
I want to install portfolioopt using pip, But I keep getting the same error. 
This is the error: 

error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\link.exe' failed with exit status 1181
  ----------------------------------------
  Failed building wheel for cvxopt

I have looked up forums and installed all possible extensions of Microsoft Visual Studio 2017 with C++, but it is still not working. 
What else do I need to do to install cvopt properly?
Many thanks in advance.

**Comment by lwsdegithub** [comment]
How it can connect with visual studio code? or c++?

**Comment by czielinski** [comment]
I'm afraid I cannot help you. If you cannot build `cvxopt`, you should probably contact the maintainers of `cvxopt` themselves.
